name: Golang CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: read
  id-token: write
  statuses: write

jobs:
  build:
    uses: ./.github/workflows/deploy.yaml
    with:
      ecs-cluster: "default"
      ecs-service: "golang-test-service"
      task-definition-family: "golang-test-family"
      image-tag: "sha-01029d6"
    secrets:
      assume-role: ${{ secrets.ASSUME_ROLE }}