name: Golang CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: read
  id-token: write
  statuses: write

jobs:
  lint:
    uses: ./.github/workflows/golangci-lint.yaml
    with:
      go-version: 'stable'
      use-private-modules: true
      github-username: 'rohit-ng'
    secrets:
      GH_TOKEN: ${{ secrets.TOKEN_FOR_GITHUB }}

  test:
    uses: ./.github/workflows/golangci-test.yaml
    with:
      go-version: 'stable'
      use-private-modules: true
      github-username: 'rohit-ng'
    secrets:
      GH_TOKEN: ${{ secrets.TOKEN_FOR_GITHUB }}

  build:
    uses: ./.github/workflows/build.yaml
    with:
      ecr-repository: 'golang'
      dockerfile: './Dockerfile'
      prefix: 'sha'
      type: 'sha'
      use-private-module: true
      github-username: 'rohit-ng'
    secrets:
      assume-role: ${{ secrets.ASSUME_ROLE }}
      GH_TOKEN: ${{ secrets.TOKEN_FOR_GITHUB }}