name: Golang CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    uses: ./.github/workflows/golangci-lint.yaml
    with:
      go-version: 'stable'
